[package]
name = "libwinit"
version = "1.0.0"
edition = "2024"

[lib]
crate-type = ["cdylib", "staticlib"]
path = "src/nativeMain/rust/lib.rs"

[dependencies]
uniffi = "0.30.0"
winit = "0.30.12"
raw-window-handle = "0.6"
